definitions:
  customTypes.File:
    properties:
      name:
        type: string
      path:
        type: string
      storage_name:
        type: string
    type: object
  customTypes.FilesResponse:
    properties:
      results:
        properties:
          data:
            items:
              $ref: '#/definitions/customTypes.File'
            type: array
          message:
            type: string
        type: object
    type: object
  pkg.HttpError:
    properties:
      description:
        type: string
      statusCode:
        type: integer
    type: object
info:
  contact: {}
paths:
  /dirs:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.HttpError'
      summary: Create dir
      tags:
      - dirs
  /dirs/{name}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/customTypes.FilesResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.HttpError'
      summary: Get dir
      tags:
      - dirs
  /files:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/customTypes.FilesResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.HttpError'
      summary: Delete file
      tags:
      - files
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/customTypes.FilesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.HttpError'
      summary: Get all files
      tags:
      - files
    post:
      parameters:
      - description: File to store
        in: formData
        name: file
        required: true
        type: file
      - description: path to store things
        in: formData
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/customTypes.FilesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.HttpError'
      summary: add a file
      tags:
      - files
  /files/{id}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/customTypes.FilesResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg.HttpError'
      summary: Get file by id
      tags:
      - files
swagger: "2.0"
